### ISSUE TITLE
Last Test from the Discussion Slides

### ISSUE THREAD

**Issue by JamesMcDougallJr** [aunnnn/cse120pa3tests#1]
I don't think the last test case from the week 5 discussion slides was covered by the current test cases. For example,

/* Order of completion should be 1, 3, 2 */
void test2() {
  InitRoad();
  if (Fork() == 0) {
    Delay(0);
    DPrintf("Process 2 finished delay\n");
    driveRoad(WEST, 40); // process 2
    Exit();
  }
  if(Fork() == 0) {
    Delay(1);
    DPrintf("Process 3 finished delay\n");
    driveRoad(EAST, 40); // process 3
    Exit();
  }
  driveRoad(WEST, 40); // process 1
  Exit();
}

Here process 3 arrives slightly after process 2, but it should still be allowed to go first (after process 1) to avoid starvation.

**Comment by aunnnn** [comment]
Hi! I guess this is similar to Test12()? 

I.e. where Car 1 is very slow from WEST, then Car 2 arrives WEST after, but couldn't take off. Then Car 3 arrives and it should go after 1. (1,3,2)
```c
void Test12() {
    DPrintf("TEST: From discussion, 1 arrives west but VERY slow. 2 arrives west too but CANNOT take off. Then 3 arrives east so it can go before 2\n");

    if (Fork() == 0) {
        Delay(100);
        DPrintf("\n>> 2 arrives from WEST\n\n");
        driveRoad(WEST, 100);
        Exit();
    }

    if (Fork() == 0) {
        Delay(120);
        DPrintf("\n>> 3 arrives from EAST\n\n");
        driveRoad(EAST, 100);
        Exit();
    }

    DPrintf("\n>> 1 arrives from WEST\n\n");
    driveRoad(WEST, 10); // Slow A!
}
```

**Comment by JamesMcDougallJr** [comment]
Thanks for pointing that out. Interestingly, though, my code was at times passing test12 while failing the one I put above. So it may be interesting nonetheless. Best of luck with the PA though!

**Comment by aunnnn** [comment]
Ahh I see. I'll check that out. Thanks for bringing this up and best of luck!
